/**
 * LocalVideoClip — embed an LTX-Video-generated MP4 as a scene.
 *
 * The MP4 is generated by tools/video-gen/local-ltx.py and lives under public/<project>/.
 * Optional text overlay (tokenized to active visual style) for captions/lower-thirds.
 *
 * For declarative workflow: declare scene type "local-video-clip" in script.json
 * with a `prompt` prop. The render-director generates the clip if missing,
 * then this scene plays it.
 */

import * as React from "react";
import { AbsoluteFill, Video, staticFile, useCurrentFrame, useVideoConfig, interpolate } from "remotion";
import { useStyleTokens } from "../lib/tokens";
import { fadeIn, sceneOpacity, defaultPacing } from "../lib/animations";
import type { LoadedFonts } from "../lib/fonts";

export interface LocalVideoClipProps {
  /** Path to generated MP4 under public/ */
  video_src: string;
  /** Original prompt (documentation only — not used at render time) */
  prompt?: string;
  /** Optional text overlay */
  overlay_text?: string;
  /** Optional eyebrow above overlay text */
  overlay_eyebrow?: string;
  /** Position of overlay */
  overlay_position?: "bottom-left" | "bottom-center" | "top-left" | "center";
  /** Darken video (0-1) for legibility behind overlay text */
  overlay_dim?: number;
  /** Apply Ken Burns zoom on top of the clip (additive motion) */
  ken_burns?: boolean;
  /** Loop video if shorter than scene duration */
  loop?: boolean;
  /** Mute the video's audio (LTX doesn't generate audio anyway) */
  muted?: boolean;
  scene_duration_frames?: number;
  fonts: LoadedFonts;
}

export const LocalVideoClip: React.FC<LocalVideoClipProps> = ({
  video_src,
  overlay_text,
  overlay_eyebrow,
  overlay_position = "bottom-left",
  overlay_dim = 0,
  ken_burns = false,
  loop = false,
  muted = true,
  scene_duration_frames,
  fonts,
}) => {
  const t = useStyleTokens();
  const frame = useCurrentFrame();
  const { fps, durationInFrames } = useVideoConfig();
  const total = scene_duration_frames ?? durationInFrames;
  const { inFrames, outFrames } = defaultPacing(t, fps);
  const op = sceneOpacity(frame, 0, total, inFrames, outFrames);

  const eyebrowOp = fadeIn(frame, Math.round(inFrames * 0.5), inFrames * 0.7);
  const overlayOp = fadeIn(frame, Math.round(inFrames * 0.7), inFrames);

  const kbScale = ken_burns
    ? interpolate(frame, [0, total], [1.0, 1.08], { extrapolateRight: "clamp" })
    : 1;

  const justify =
    overlay_position.startsWith("top") ? "flex-start" :
    overlay_position.startsWith("bottom") ? "flex-end" :
    "center";
  const align =
    overlay_position.endsWith("left") ? "flex-start" :
    overlay_position.endsWith("center") ? "center" :
    "flex-end";

  return (
    <AbsoluteFill style={{ backgroundColor: t.colors.heading, opacity: op }}>
      <Video
        src={staticFile(video_src)}
        muted={muted}
        loop={loop}
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          objectFit: "cover",
          transform: `scale(${kbScale})`,
        }}
      />

      {overlay_dim > 0 && (
        <div
          style={{
            position: "absolute",
            inset: 0,
            backgroundColor: t.colors.heading,
            opacity: overlay_dim,
          }}
        />
      )}

      {(overlay_text || overlay_eyebrow) && (
        <div
          style={{
            position: "absolute",
            inset: 0,
            padding: "10%",
            display: "flex",
            flexDirection: "column",
            justifyContent: justify,
            alignItems: align,
            pointerEvents: "none",
          }}
        >
          {overlay_eyebrow && (
            <div
              style={{
                fontFamily: fonts.body,
                fontWeight: 500,
                fontSize: 22,
                letterSpacing: "0.22em",
                textTransform: "uppercase",
                color: "#ffffff",
                marginBottom: 22,
                opacity: eyebrowOp,
                textAlign: align === "center" ? "center" : "left",
                textShadow: "0 1px 8px rgba(0,0,0,0.4)",
              }}
            >
              {overlay_eyebrow}
            </div>
          )}
          {overlay_text && (
            <div
              style={{
                fontFamily: fonts.display,
                fontWeight: 500,
                fontSize: t.layout.hero.font_size_px,
                lineHeight: t.layout.hero.line_height,
                letterSpacing: `${t.layout.hero.letter_spacing_em}em`,
                color: "#ffffff",
                textShadow: "0 2px 14px rgba(0,0,0,0.5)",
                opacity: overlayOp,
                maxWidth: "92%",
                textAlign: align === "center" ? "center" : "left",
              }}
            >
              {overlay_text}
            </div>
          )}
        </div>
      )}
    </AbsoluteFill>
  );
};

export const LocalVideoClipSchema = {
  video_src: { type: "string", required: true },
  prompt: { type: "string", required: false },
  overlay_text: { type: "string", required: false },
  overlay_eyebrow: { type: "string", required: false },
  overlay_position: {
    type: "enum",
    values: ["bottom-left", "bottom-center", "top-left", "center"],
    required: false,
  },
  overlay_dim: { type: "number", required: false },
  ken_burns: { type: "boolean", required: false },
  loop: { type: "boolean", required: false },
  muted: { type: "boolean", required: false },
} as const;
