/**
 * demo-local-video — validates the local-video-clip scene with an LTX-generated MP4.
 *
 * The MP4 at public/demo-local-video/ltx-clip.mp4 is generated by:
 *   avg local-video generate --prompt "..." --to compositions/public/demo-local-video/ltx-clip.mp4
 */

import * as React from "react";
import { AbsoluteFill, Sequence } from "remotion";
import { StyleProvider } from "../../lib/tokens";
import { loadFontsForStyle } from "../../lib/fonts";
import { HeroTitle } from "../../scenes/HeroTitle";
import { LocalVideoClip } from "../../scenes/LocalVideoClip";
import { TextCard } from "../../scenes/TextCard";
import { ClosingCard } from "../../scenes/ClosingCard";
import { TOKENS } from "./tokens";

const FPS = 30;
const TOTAL_FRAMES = 12 * FPS;
const fonts = loadFontsForStyle(TOKENS);
const f = (s: number) => Math.round(s * FPS);

export const meta = {
  id: "demo-local-video",
  durationInFrames: TOTAL_FRAMES,
  fps: FPS,
  width: 1920,
  height: 1080,
};

const Project: React.FC = () => (
  <StyleProvider tokens={TOKENS}>
    <AbsoluteFill style={{ backgroundColor: TOKENS.colors.bg }}>
      <Sequence from={f(0)} durationInFrames={f(2)}>
        <HeroTitle
          eyebrow="GENERADO LOCALMENTE · LTX-VIDEO 2.0"
          product_wordmark="b-roll"
          layout="horizontal"
          scene_duration_frames={f(2)}
          fonts={fonts}
        />
      </Sequence>

      <Sequence from={f(2)} durationInFrames={f(4)}>
        <LocalVideoClip
          video_src="demo-local-video/ltx-clip.mp4"
          prompt="Slow cinematic dolly across an empty modernist office at golden hour"
          overlay_eyebrow="GENERADO POR LTX EN ~5 MIN · M4 PRO"
          overlay_text="Sin APIs."
          overlay_position="bottom-left"
          overlay_dim={0.35}
          ken_burns
          loop
          scene_duration_frames={f(4)}
          fonts={fonts}
        />
      </Sequence>

      <Sequence from={f(6)} durationInFrames={f(3)}>
        <TextCard
          lines={["El video ya no es un asset que compras.", "Es algo que pides."]}
          emphasis_line={1}
          alignment="center"
          scene_duration_frames={f(3)}
          fonts={fonts}
        />
      </Sequence>

      <Sequence from={f(9)} durationInFrames={f(3)}>
        <ClosingCard
          product_wordmark="DELTA"
          brand_wordmark="autarqui"
          brand_wordmark_ext=".co"
          scene_duration_frames={f(3)}
          fonts={fonts}
        />
      </Sequence>
    </AbsoluteFill>
  </StyleProvider>
);

export default Project;
