/**
 * audio.ts — Reusable music volume curves.
 *
 * Curves are matched to the visual-style.md `audio.music_curve` token.
 * Used by the Composition.tsx generated by render-director per project.
 */

import { interpolate } from "remotion";

export type CurvePreset = "editorial" | "punchy" | "cinematic" | "silent";

export interface CurveOptions {
  fps: number;
  /** Frame at which fade-in begins. */
  fadeInFrame: number;
  /** Frame at which music reaches full volume. */
  fullVolumeFrame: number;
  /** Frame at which fade-out begins (or hard cut, depending on curve). */
  fadeOutStartFrame: number;
  /** Frame at which music reaches silence. */
  fadeOutEndFrame: number;
  /** Peak volume (0..1). */
  peak?: number;
}

/**
 * Returns a `(frame: number) => volume` function ready to pass to Remotion's
 * <Audio volume={...}> prop.
 */
export function buildMusicCurve(preset: CurvePreset, opts: CurveOptions): (f: number) => number {
  const peak = opts.peak ?? 1;

  switch (preset) {
    case "editorial":
      // Slow ramp in, hold, long musical decay (eased).
      return (f: number) => {
        if (f < opts.fadeInFrame) return 0;
        if (f < opts.fullVolumeFrame) {
          return interpolate(
            f,
            [opts.fadeInFrame, opts.fullVolumeFrame],
            [0, peak],
            { extrapolateRight: "clamp" },
          );
        }
        if (f < opts.fadeOutStartFrame) return peak;
        if (f < opts.fadeOutEndFrame) {
          const t = (f - opts.fadeOutStartFrame) / (opts.fadeOutEndFrame - opts.fadeOutStartFrame);
          const eased = 1 - Math.pow(t, 1.6);
          return Math.max(0, peak * eased);
        }
        return 0;
      };

    case "punchy":
      // Faster ramp, near-hard cut at end (last 0.2s).
      return (f: number) => {
        if (f < opts.fadeInFrame) return 0;
        if (f < opts.fullVolumeFrame) {
          return interpolate(
            f,
            [opts.fadeInFrame, opts.fullVolumeFrame],
            [0, peak],
            { extrapolateRight: "clamp" },
          );
        }
        if (f < opts.fadeOutStartFrame) return peak;
        if (f < opts.fadeOutEndFrame) {
          return interpolate(
            f,
            [opts.fadeOutStartFrame, opts.fadeOutEndFrame],
            [peak, 0],
            { extrapolateRight: "clamp" },
          );
        }
        return 0;
      };

    case "cinematic":
      // Long crescendo, hold, slow tail-out.
      return (f: number) => {
        if (f < opts.fadeInFrame) return 0;
        if (f < opts.fullVolumeFrame) {
          // Quadratic crescendo — feels more "musical" than linear
          const t = (f - opts.fadeInFrame) / (opts.fullVolumeFrame - opts.fadeInFrame);
          return peak * t * t;
        }
        if (f < opts.fadeOutStartFrame) return peak;
        if (f < opts.fadeOutEndFrame) {
          const t = (f - opts.fadeOutStartFrame) / (opts.fadeOutEndFrame - opts.fadeOutStartFrame);
          const eased = 1 - Math.pow(t, 2.2);
          return Math.max(0, peak * eased);
        }
        return 0;
      };

    case "silent":
    default:
      return () => 0;
  }
}

// ============================================================================
// trimBefore calculator (for end-of-track alignment)
// ============================================================================

/**
 * Compute the audio `trimBefore` (in frames) so the natural end of the audio
 * file lines up with `endFrame` of the video.
 *
 * Validated approach: if the music has a natural musical resolution, aligning
 * its END with a key visual moment (closing line, before logo) makes the
 * cut feel inevitable instead of arbitrary.
 */
export function calcTrimBefore(opts: {
  audioFileDurationS: number;
  startFrame: number;
  endFrame: number;
  fps: number;
}): number {
  const playLengthFrames = opts.endFrame - opts.startFrame;
  const playLengthS = playLengthFrames / opts.fps;
  const trimS = Math.max(0, opts.audioFileDurationS - playLengthS);
  return Math.round(trimS * opts.fps);
}
